hello: 
	echo "hello"

format:
	terraform fmt

check-format:
	terraform init
	terraform validate

output:
	terraform output

deploy:
	terraform fmt
	terraform init
	terraform apply --auto-approve